@rmdir /s /q CMakeFiles
@rmdir /s /q Debug
#@rmdir /s /q Release
@rmdir /s /q spmbpOF.dir
@rmdir /s /q x64
@del /f /q spmbpOF*
@del /f /q ALL_BUILD*
@del /f /q ZERO_CHECK*
@del /f /q cmake_install.cmake
@del /f /q CMakeCache.txt